import = ["/home/matt/.config/alacritty/colors.toml", "/home/matt/.config/alacritty/fonts.toml"]
live_config_reload = true

[shell]
program = "/bin/zsh"
args = ["-l"] 

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_title = true
startup_mode = "Windowed"
opacity = 0.90

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 12
y = 12
